Apps/urls.py
from django.urls import path
from .views import *

app_name = "Apps"

urlpatterns = [
    path("", HomveView.as_view(), name="index"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("eabout/", EmpolyerAboutView.as_view(), name="eabout"),
    path("jabout/", JobseekerAboutView.as_view(), name="jabout"),
    path("econtact/", EmployerContactView.as_view(), name="econtact"),
    path("jcontact/", JobseekerContactView.as_view(), name="jcontact"),
    path("jregister/", JobseekerRegistrationView.as_view(), name="jregister"),
    path("eregister/", EmployerRegister.as_view(), name="eregister"),
    path("eindex/", EmployerIndex.as_view(), name="eindex"),
    path("jindex/", JobseekerIndex.as_view(), name="jindex"),
    path("postjob/", PostJobView.as_view(), name="postjob"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/",LogoutView.as_view(),name="logout"),
    path("singlejob/<int:pk>/",SingleJobView.as_view(),name="singlejob"),
    path("job/<int:pk>/apply/", JobApplyView.as_view(),name="apply"),
    path("search/", JobSearchView.as_view(),name="search"),
    path("empsinglejob/<int:pk>/", EmpSingleJobView.as_view(),name="empsinglejob"),
    path("jsinglejob/<int:pk>/", JobseekerSingleJobView.as_view(),name="jsinglejob"),
    

    
    
]

JobPortalSystem/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Apps.urls")),

    
] 
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

templates/Home/about.html
{% extends 'base.html' %} 
{% load static %}

{% block nav %} 
<!-- NAVBAR -->
<header class="site-navbar mt-3">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="site-logo col-6"><a href="/">JobBoard</a></div>

      <nav class="mx-auto site-navigation">
        <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
          <li><a href="/" >Home</a></li>
          <li><a href="/about/" class="nav-link active">About</a></li>
          <li class="has-children">
            {% comment %} <a href="job-listings.html">Categories</a>
            <ul class="dropdown">
              <li><a href="job-single.html">Job Single</a></li>
              <li><a href="post-job.html">Post a Job</a></li>
            </ul> {% endcomment %}
          </li>
          <li><a href="/contact/">Contact</a></li>
          <li class="has-children">
            <a href="#">Register</a>
            <ul class="dropdown">
              <li><a href="/eregister/">Employee</a></li>
              <li><a href="/jregister/">Jobseeks</a></li>
              
            </ul>
          </li>
          {% comment %} <li><a href="blog.html">Blog</a></li> {% endcomment %}
          <li class="d-lg-none"><a href="/postjob/"><span class="mr-2">+</span> Post a Job</a></li>
          <li class="d-lg-none"><a href="/login/">Login</a></li>
        </ul>
      </nav>
      
      <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
        <div class="ml-auto">
          <a href="/postjob/" class="btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-add"></span>Post a Job</a>
          <a href='/login/' class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-lock_outline"></span>Login</a>
        </div>
        <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span></a>
      </div>

    </div>
  </div>
</header>
{% endblock nav %}

{% block content %} 

    <!-- HOME -->
    <section class="section-hero overlay inner-page bg-image" style="background-image: url('/static/images/job/hero_1.jpg');" id="home-section">
        <div class="container">
          <div class="row">
            <div class="col-md-7">
              <h1 class="text-white font-weight-bold">About Us</h1>
              <div class="custom-breadcrumbs">
                <a href="#">Home</a> <span class="mx-2 slash">/</span>
                <span class="text-white"><strong>About Us</strong></span>
              </div>
            </div>
          </div>
        </div>
      </section>
  
     
  
      
      <section class="site-section pb-0">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-lg-6 mb-5 mb-lg-0">
              <a data-fancybox data-ratio="2" href="https://vimeo.com/317571768" class="block__96788">
                <span class="play-icon"><span class="icon-play"></span></span>
                <img src="/static/images/job/sq_img_6.jpg" alt="Image" class="img-fluid img-shadow">
              </a>
            </div>
            <div class="col-lg-5 ml-auto">
              <h2 class="section-title mb-3">JobBoard For Freelancers, Web Developers</h2>
              <p class="lead">Eveniet voluptatibus voluptates suscipit minima, cum voluptatum ut dolor, sed facere corporis qui, ea quisquam quis odit minus nulla vitae. Sit, voluptatem.</p>
              <p>Ipsum harum assumenda in eum vel eveniet numquam, cumque vero vitae enim cupiditate deserunt eligendi officia modi consectetur. Expedita tempora quos nobis earum hic ex asperiores quisquam optio nostrum sit!</p>
            </div>
          </div>
        </div>
      </section>
  
      <section class="site-section pt-0">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-lg-6 mb-5 mb-lg-0 order-md-2">
              <a data-fancybox data-ratio="2" href="https://vimeo.com/317571768" class="block__96788">
                <span class="play-icon"><span class="icon-play"></span></span>
                <img src="/static/images/job/sq_img_8.jpg" alt="Image" class="img-fluid img-shadow">
              </a>
            </div>
            <div class="col-lg-5 mr-auto order-md-1  mb-5 mb-lg-0">
              <h2 class="section-title mb-3">JobBoard For Workers</h2>
              <p class="lead">Eveniet voluptatibus voluptates suscipit minima, cum voluptatum ut dolor, sed facere corporis qui, ea quisquam quis odit minus nulla vitae. Sit, voluptatem.</p>
              <p>Ipsum harum assumenda in eum vel eveniet numquam, cumque vero vitae enim cupiditate deserunt eligendi officia modi consectetur. Expedita tempora quos nobis earum hic ex asperiores quisquam optio nostrum sit!</p>
            </div>
          </div>
        </div>
      </section>
  
     
      <section class="site-section">
        <div class="container">
          <div class="row mb-5">
            <div class="col-12 text-center" data-aos="fade">
              <h2 class="section-title mb-3">Our Team</h2>
            </div>
          </div>
  
          <div class="row align-items-center block__69944">
  
            <div class="col-md-6">
              <img src="/static/images/job/person_6.jpg" alt="Image" class="img-fluid mb-4 rounded">
            </div>
  
            <div class="col-md-6">
              <h3>Elisabeth Smith</h3>
              <p class="text-muted">Creative Director</p>
              <p>Soluta quasi cum delectus eum facilis recusandae nesciunt molestias accusantium libero dolores repellat id in dolorem laborum ad modi qui at quas dolorum voluptatem voluptatum repudiandae voluptatibus ut? Ex vel  ad explicabo iure ipsa possimus consectetur neque rem molestiae eligendi velit?.</p>
              <div class="social mt-4">
                <a href="#"><span class="icon-facebook"></span></a>
                <a href="#"><span class="icon-twitter"></span></a>
                <a href="#"><span class="icon-instagram"></span></a>
                <a href="#"><span class="icon-linkedin"></span></a>
              </div>
            </div>
  
            <div class="col-md-6 order-md-2 ml-md-auto">
              <img src="/static/images/job/person_5.jpg" alt="Image" class="img-fluid mb-4 rounded">
            </div>
  
            <div class="col-md-6">
              <h3>Chintan Patel</h3>
              <p class="text-muted">Creative Director</p>
              <p>Soluta quasi cum delectus eum facilis recusandae nesciunt molestias accusantium libero dolores repellat id in dolorem laborum ad modi qui at quas dolorum voluptatem voluptatum repudiandae voluptatibus ut? Ex vel  ad explicabo iure ipsa possimus consectetur neque rem molestiae eligendi velit?.</p>
              <div class="social mt-4">
                <a href="#"><span class="icon-facebook"></span></a>
                <a href="#"><span class="icon-twitter"></span></a>
                <a href="#"><span class="icon-instagram"></span></a>
                <a href="#"><span class="icon-linkedin"></span></a>
              </div>
            </div>
        </div>
      </section>
  
{% endblock content %}

templates/Home/contact.html
{% extends 'base.html' %} 
{% load static %}


{% block nav %} 
<!-- NAVBAR -->
<header class="site-navbar mt-3">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="site-logo col-6"><a href="/">JobBoard</a></div>

      <nav class="mx-auto site-navigation">
        <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
          <li><a href="/" >Home</a></li>
          <li><a href="/about/">About</a></li>
          <li class="has-children">
            {% comment %} <a href="job-listings.html">Categories</a>
            <ul class="dropdown">
              <li><a href="job-single.html">Job Single</a></li>
              <li><a href="post-job.html">Post a Job</a></li>
            </ul> {% endcomment %}
          </li>
          <li><a href="/contact/" class="nav-link active">Contact</a></li>
          <li class="has-children">
            <a href="#">Register</a>
            <ul class="dropdown">
              <li><a href="/eregister/">Employee</a></li>
              <li><a href="/jregister/">Jobseeks</a></li>
              
            </ul>
          </li>
          {% comment %} <li><a href="blog.html">Blog</a></li> {% endcomment %}
          <li class="d-lg-none"><a href="/postjob/"><span class="mr-2">+</span> Post a Job</a></li>
          <li class="d-lg-none"><a href="/login/">Login</a></li>
        </ul>
      </nav>
      
      <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
        <div class="ml-auto">
          <a href="/postjob/" class="btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-add"></span>Post a Job</a>
          <a href='/login/' class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-lock_outline"></span>Login</a>
        </div>
        <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span></a>
      </div>

    </div>
  </div>
</header>
{% endblock nav %}

{% block content %} 
    <!-- HOME -->
    <section class="section-hero overlay inner-page bg-image" style="background-image: url('/static/images/job/hero_1.jpg');" id="home-section">
        <div class="container">
          <div class="row">
            <div class="col-md-7">
              <h1 class="text-white font-weight-bold">Contact Us</h1>
              <div class="custom-breadcrumbs">
                <a href="#">Home</a> <span class="mx-2 slash">/</span>
                <span class="text-white"><strong>Contact Us</strong></span>
              </div>
            </div>
          </div>
        </div>
      </section>
  
      <section class="site-section" id="next-section">
        <div class="container">
          <div class="row">
            <div class="col-lg-6 mb-5 mb-lg-0">
              <form action="" method="POST" class="" name = "contact">
                  {% csrf_token %}
                <div class="row form-group">
                  <div class="col-md-6 mb-3 mb-md-0">
                    <label class="text-black" for="fname">First Name</label>
                    <input type="text" id="fname" name = "firstname" class="form-control">
                  </div>
                  <div class="col-md-6">
                    <label class="text-black" for="lname">Last Name</label>
                    <input type="text" id="lname" name = "lastname" class="form-control">
                  </div>
                </div>
  
                <div class="row form-group">
                  
                  <div class="col-md-12">
                    <label class="text-black" for="email">Email</label> 
                    <input type="email" name = "email" id="email" class="form-control">
                  </div>
                </div>
  
                <div class="row form-group">
                  
                  <div class="col-md-12">
                    <label class="text-black" for="subject">Subject</label> 
                    <input type="subject" id="subject" name = "subject" class="form-control">
                  </div>
                </div>
  
                <div class="row form-group">
                  <div class="col-md-12">
                    <label class="text-black" for="message">Message</label> 
                    <textarea name="message" id="message" cols="30" rows="7" class="form-control" name="message"  placeholder="Write your notes or questions here..."></textarea>
                  </div>
                </div>
  
                <div class="row form-group">
                  <div class="col-md-12">
                    <input type="submit" value="Send Message" name = "contact" class="btn btn-primary btn-md text-white">
                  </div>
                </div>
  
    
              </form>
            </div>
            <div class="col-lg-5 ml-auto">
              <div class="p-4 mb-3 bg-white">
                <p class="mb-0 font-weight-bold">Address</p>
                <p class="mb-4">Nepal, Kathmandu, Baneshwor</p>
  
                <p class="mb-0 font-weight-bold">Phone</p>
                <p class="mb-4"><a href="#">+977 9808157822</a></p>
  
                <p class="mb-0 font-weight-bold">Email Address</p>
                <p class="mb-0"><a href="#">priyatamang565@gmail.com</a></p>
  
              </div>
            </div>
          </div>
        </div>
      </section>
{% endblock content %}

templates/Home/index.html
{% extends 'base.html' %} 
{% load static %}


{% block nav %} 
<!-- NAVBAR -->
<header class="site-navbar mt-3">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="site-logo col-6"><a href="/">JobBoard</a></div>

      <nav class="mx-auto site-navigation">
        <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
          <li><a href="/" class="nav-link active">Home</a></li>
          <li><a href="/about/">About</a></li>
          <li class="has-children">
            {% comment %} <a href="job-listings.html">Categories</a>
            <ul class="dropdown">
              <li><a href="job-single.html">Job Single</a></li>
              <li><a href="post-job.html">Post a Job</a></li>
            </ul> {% endcomment %}
          </li>
          <li><a href="/contact/">Contact</a></li>
          <li class="has-children">
            <a href="#">Register</a>
            <ul class="dropdown">
              <li><a href="/eregister/">Employee</a></li>
              <li><a href="/jregister/">Jobseeks</a></li>
              
            </ul>
          </li>
          {% comment %} <li><a href="blog.html">Blog</a></li> {% endcomment %}
          <li class="d-lg-none"><a href="/postjob/"><span class="mr-2">+</span> Post a Job</a></li>
          <li class="d-lg-none"><a href="/login/">Login</a></li>
        </ul>
      </nav>
      
      <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
        <div class="ml-auto">
          <a href="/postjob/" class="btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-add"></span>Post a Job</a>
          <a href='/login/' class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-lock_outline"></span>Login</a>
        </div>
        <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span></a>
      </div>

    </div>
  </div>
</header>
{% endblock nav %}

{% block content %} 

 <!-- HOME -->
 <section class="home-section section-hero overlay bg-image" style="background-image: url('/static/images/job/hero_1.jpg');" id="home-section">

  <div class="container">
    <div class="row align-items-center justify-content-center">
      <div class="col-md-12">
        <div class="mb-5 text-center">
          <h1 class="text-white font-weight-bold">The Easiest Way To Get Your Dream Job</h1>
          {% comment %} <p>Because people are our most precious assets… we only let the best managers in the world lead them</p> {% endcomment %}
        </div>
        <form method="GET" class="search-jobs-form"  name="search" action="/search/" value="{{request.GET.search}}" >
          {% csrf_token %}
          <div class="row mb-5">
            <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
              <input type="text" name = "job_title" class="form-control form-control-lg" placeholder="Job title">
            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
              <select class="selectpicker" data-style="btn-white btn-lg" name="location" data-width="100%" data-live-search="true" title="Select Location">
                <option value = "Anywhere">Anywhere</option>
                <option value = "Kathmandu">Kathmandu</option>
                <option value = "Bhaktapur">Bhaktapur</option>
                <option value = "Chabahil">Chabahil</option>
                <option value = "Koteshwor">Koteshwor</option>
                <option value = "Baneshwor">Baneshwor</option>
                <option value = "Kalanki">Kalanki</option>
                <option value = "Gorkha">Gorkha</option>
                <option value = "Pokhara">Pokhara</option>
              </select>
            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
              <select class="selectpicker" data-style="btn-white btn-lg" name = "job_type" data-width="100%" data-live-search="true" title="Select Job Type">
                <option value ="Part Time">Part Time</option>
                <option value = "Full Time">Full Time</option>
              </select>
            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
              <Input type="submit" class="btn btn-primary btn-lg btn-block text-white btn-search" name = "search" value = "Search"></span>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

  <a href="#next" class="scroll-button smoothscroll">
    <span class=" icon-keyboard_arrow_down"></span>
  </a>

</section>

<section class="py-5 bg-image overlay-primary fixed overlay" id="next" style="background-image: url=("{% static '/static/images/job/hero_1.jpg' %}");">
  <div class="container">
    <div class="row mb-5 justify-content-center">
      <div class="col-md-7 text-center">
        <h2 class="section-title mb-2 text-white">JobBoard Site Stats</h2>
        <p class="lead text-white">Because people are our most precious assets… We only let the best managers in the world lead them</p>
      </div>
    </div>
    <div class="row pb-0 block__19738 section-counter">
 {% for c in count%}
      <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
        <div class="d-flex align-items-center justify-content-center mb-2">
          <strong class="number" data-number="{{c.candidatescount}}">0</strong>
        </div>
        <span class="caption">Candidates</span>
      </div>
      {% endfor %}

      <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
        <div class="d-flex align-items-center justify-content-center mb-2">
          <strong class="number" data-number="54">0</strong>
        </div>
        <span class="caption">Jobs Posted</span>
      </div>

      <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
        <div class="d-flex align-items-center justify-content-center mb-2">
          <strong class="number" data-number="120">0</strong>
        </div>
        <span class="caption">Jobs Filled</span>
      </div>

      <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
        <div class="d-flex align-items-center justify-content-center mb-2">
          <strong class="number" data-number="550">0</strong>
        </div>
        <span class="caption">Companies</span>
      </div>

        
    </div>
  </div>
</section>



<section class="site-section">
  <div class="container">

    <div class="row mb-5 justify-content-center">
      <div class="col-md-7 text-center">
        <h2 class="section-title mb-2">43,167 Job Listed</h2>
      </div>
    </div>
    {% for n in newjob %}
    <ul class="job-listings mb-5">
      <li class="job-listing d-block d-sm-flex pb-3 pb-sm-0 align-items-center">
        <a href="{% url 'Apps:singlejob' n.id %}"></a>
        <div class="job-listing-logo">
          {% if n.logo %}
          <img src="{{n.logo.url}}" alt="Free Website Template by Free-Template.co" class="img-fluid">
          {% endif %}
        </div>
        

        <div class="job-listing-about d-sm-flex custom-width w-100 justify-content-between mx-4">
          <div class="job-listing-position custom-width w-50 mb-3 mb-sm-0">
            <h2>{{n.job_title}}</h2>
            <br>
            <strong>{{n.company_name}}</strong> 
          </div>
          <div class="job-listing-location mb-3 mb-sm-0 custom-width w-25">
            <span class="icon-room"></span> {{n.location}}
          </div>
          <div class="job-listing-meta">
            <span class="badge badge-danger">{{n.job_type}}</span>
            {% comment %} <span class="badge badge-danger">{{n.job_type}}</span> {% endcomment %}
          </div>
        </div>        
      </li>

        {% endfor %}

    
    <div class="row pagination-wrap">
      <div class="col-md-6 text-center text-md-left mb-4 mb-md-0">
        <span>Showing 1-7 Of 43,167 Jobs</span>
      </div>
      <div class="col-md-6 text-center text-md-right">
        <div class="custom-pagination ml-auto">
          <a href="#" class="prev">Prev</a>
          <div class="d-inline-block">
          <a href="#" class="active">1</a>
          <a href="#">2</a>
          <a href="#">3</a>
          <a href="#">4</a>
          </div>
          <a href="#" class="next">Next</a>
        </div>
      </div>
    </div>

  </div>
</section>

<section class="py-5 bg-image overlay-primary fixed overlay" style="background-image: url('static/images/job/hero_1.jpg');">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-8">
        <h2 class="text-white">Looking For A Job?</h2>
        <p class="mb-0 text-white lead"></p>
      </div>
      <div class="col-md-3 ml-auto">
        <a href="/login/" class="btn btn-warning btn-block btn-lg">Log In</a>
      </div>
    </div>
  </div>
</section>


{% endblock content %}

templates/Home/search.html
{% extends 'base.html' %} 
{% load static %}

{% block nav %} 
<!-- NAVBAR -->
<header class="site-navbar mt-3">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="site-logo col-6"><a href="/">JobBoard</a></div>

      <nav class="mx-auto site-navigation">
        <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
          <li><a href="/" class="nav-link active">Home</a></li>
          <li><a href="#">About</a></li>
          <li class="has-children">
            {% comment %} <a href="job-listings.html">Categories</a>
            <ul class="dropdown">
              <li><a href="job-single.html">Job Single</a></li>
              <li><a href="post-job.html">Post a Job</a></li>
            </ul> {% endcomment %}
          </li>
          <li><a href="#">Contact</a></li>
          <li class="has-children">
            <a href="#">Register</a>
            <ul class="dropdown">
              <li><a href="/eregister/">Employee</a></li>
              <li><a href="/jregister/">Jobseeks</a></li>
              
            </ul>
          </li>
          {% comment %} <li><a href="blog.html">Blog</a></li> {% endcomment %}
          <li class="d-lg-none"><a href="/postjob/"><span class="mr-2">+</span> Post a Job</a></li>
          <li class="d-lg-none"><a href="/login/">Login</a></li>
        </ul>
      </nav>
      
      <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
        <div class="ml-auto">
          <a href="/postjob/" class="btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-add"></span>Post a Job</a>
          <a href='/login/' class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-lock_outline"></span>Login</a>
        </div>
        <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span></a>
      </div>

    </div>
  </div>
</header>
{% endblock nav %}

{% block content %} 
<section class="section-hero overlay inner-page bg-image" style="background-image: url('/static/images/job/hero_1.jpg');"  id="home-section">  
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1 class="text-white font-weight-bold">Search</h1>
        <div class="custom-breadcrumbs">
          <a href="#">Home</a> <span class="mx-2 slash">/</span>
          <a href="#">Job</a> <span class="mx-2 slash">/</span>
          <span class="text-white"><strong>Search</strong></span>
        </div>
      </div>
    </div>
  </div>
</section>


  <section class="site-section">
    <div class="container">
  
      <div class="row mb-5 justify-content-center">
        <div class="col-md-7 text-center">
          <h2 class="section-title mb-2">Searching List</h2>
        </div>
      </div>
      
      {% for job in search_results %}
      <ul class="job-listings mb-5">
        <li class="job-listing d-block d-sm-flex pb-3 pb-sm-0 align-items-center">
          <a href="{% url 'Apps:singlejob' job.id %}"></a> 
          <div class="job-listing-logo">
            {% if job.logo %}
            <img src="{{job.logo.url}}" alt="Free Website Template by Free-Template.co" class="img-fluid">
            {% endif %}
          </div>
  
          <div class="job-listing-about d-sm-flex custom-width w-100 justify-content-between mx-4">
            <div class="job-listing-position custom-width w-50 mb-3 mb-sm-0">
              <a href="#"><h2>Product{{job.job_title}}</h2></a>
              <br>
              <strong>{{n.company_name}}</strong> 
            </div>
            <div class="job-listing-location mb-3 mb-sm-0 custom-width w-25">
              <span class="icon-room"></span> {{job.location}}
            </div>
            <div class="job-listing-meta">
              <span class="badge badge-danger">{{job.job_type}}</span>
              {% comment %} <span class="badge badge-danger">{{n.job_type}}</span> {% endcomment %}
            </div>
          </div>        
        </li>
  
          {% endfor %}
  
      
      <div class="row pagination-wrap">
        <div class="col-md-6 text-center text-md-left mb-4 mb-md-0">
          <span>Showing 1-7 Of 43,167 Jobs</span>
        </div>
        <div class="col-md-6 text-center text-md-right">
          <div class="custom-pagination ml-auto">
            <a href="#" class="prev">Prev</a>
            <div class="d-inline-block">
            <a href="#" class="active">1</a>
            <a href="#">2</a>
            <a href="#">3</a>
            <a href="#">4</a>
            </div>
            <a href="#" class="next">Next</a>
          </div>
        </div>
      </div>
  
    </div>
  </section>

{% endblock content %}