Apps/urls.py
from django.urls import path
from .views import *

app_name = "Apps"

urlpatterns = [
    path("", HomveView.as_view(), name="index"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("eabout/", EmpolyerAboutView.as_view(), name="eabout"),
    path("jabout/", JobseekerAboutView.as_view(), name="jabout"),
    path("econtact/", EmployerContactView.as_view(), name="econtact"),
    path("jcontact/", JobseekerContactView.as_view(), name="jcontact"),
    path("jregister/", JobseekerRegistrationView.as_view(), name="jregister"),
    path("eregister/", EmployerRegister.as_view(), name="eregister"),
    path("eindex/", EmployerIndex.as_view(), name="eindex"),
    path("jindex/", JobseekerIndex.as_view(), name="jindex"),
    path("postjob/", PostJobView.as_view(), name="postjob"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/",LogoutView.as_view(),name="logout"),
    path("singlejob/<int:pk>/",SingleJobView.as_view(),name="singlejob"),
    path("job/<int:pk>/apply/", JobApplyView.as_view(),name="apply"),
    path("search/", JobSearchView.as_view(),name="search"),
    path("empsinglejob/<int:pk>/", EmpSingleJobView.as_view(),name="empsinglejob"),
    path("jsinglejob/<int:pk>/", JobseekerSingleJobView.as_view(),name="jsinglejob"),
    

    
    
]

JobPortalSystem/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Apps.urls")),

    
] 
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

templates/Emp/allcontact.html
{% extends 'base.html' %} 
{% load static %}

{% block nav %} 
<!-- NAVBAR -->
<header class="site-navbar mt-3">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="site-logo col-6"><a href="/eindex/">JobBoard</a></div>

      <nav class="mx-auto site-navigation">
        <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
          <li><a href="/eindex/" >Home</a></li>
          <li><a href="/eabout/" >About</a></li>
          <li class="has-children">
            {% comment %} <a href="job-listings.html">Categories</a>
            <ul class="dropdown">
              <li><a href="job-single.html">Job Single</a></li>
              <li><a href="post-job.html">Post a Job</a></li>
            </ul> {% endcomment %}
          </li>
          <li><a href="/econtact/" class="nav-link active">Contact</a></li>
          {% comment %} <li class="has-children">
            <a href="#">Register</a>
            <ul class="dropdown">
              <li><a href="/eregister/">Employee</a></li>
              <li><a href="/jregister/">Jobseeks</a></li>
              
            </ul> {% endcomment %}
          </li>
          {% comment %} <li><a href="blog.html">Blog</a></li> {% endcomment %}
          {% comment %} <li class="d-lg-none"><a href="/postjob/"><span class="mr-2">+</span> Post a Job</a></li> {% endcomment %}
          <li class="d-lg-none"><a href="/logout/">Logout</a></li>
        </ul>
      </nav>
      
      <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
        <div class="ml-auto">
          {% comment %} <a href="/postjob/" class="btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-add"></span>Post a Job</a> {% endcomment %}
          <a href='/logout/' class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-lock_outline"></span>Login</a>
        </div>
        <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span></a>
      </div>

    </div>
  </div>
</header>
{% endblock nav %}

{% block content %} 
    <!-- HOME -->
    <section class="section-hero overlay inner-page bg-image" style="background-image: url('/static/images/job/hero_1.jpg');" id="home-section">
        <div class="container">
          <div class="row">
            <div class="col-md-7">
              <h1 class="text-white font-weight-bold">Contact Us</h1>
              <div class="custom-breadcrumbs">
                <a href="#">Home</a> <span class="mx-2 slash">/</span>
                <span class="text-white"><strong>Contact Us</strong></span>
              </div>
            </div>
          </div>
        </div>
      </section>
  
      <section class="site-section" id="next-section">
        <div class="container">
          <div class="row">
            <div class="col-lg-6 mb-5 mb-lg-0">
              <form action="#" class="">
  
                <div class="row form-group">
                  <div class="col-md-6 mb-3 mb-md-0">
                    <label class="text-black" for="fname">First Name</label>
                    <input type="text" id="fname" class="form-control">
                  </div>
                  <div class="col-md-6">
                    <label class="text-black" for="lname">Last Name</label>
                    <input type="text" id="lname" class="form-control">
                  </div>
                </div>
  
                <div class="row form-group">
                  
                  <div class="col-md-12">
                    <label class="text-black" for="email">Email</label> 
                    <input type="email" id="email" class="form-control">
                  </div>
                </div>
  
                <div class="row form-group">
                  
                  <div class="col-md-12">
                    <label class="text-black" for="subject">Subject</label> 
                    <input type="subject" id="subject" class="form-control">
                  </div>
                </div>
  
                <div class="row form-group">
                  <div class="col-md-12">
                    <label class="text-black" for="message">Message</label> 
                    <textarea name="message" id="message" cols="30" rows="7" class="form-control" placeholder="Write your notes or questions here..."></textarea>
                  </div>
                </div>
  
                <div class="row form-group">
                  <div class="col-md-12">
                    <input type="submit" value="Send Message" class="btn btn-primary btn-md text-white">
                  </div>
                </div>
  
    
              </form>
            </div>
            <div class="col-lg-5 ml-auto">
              <div class="p-4 mb-3 bg-white">
                <p class="mb-0 font-weight-bold">Address</p>
                <p class="mb-4">Nepal, Kathmandu, Baneshwor</p>
  
                <p class="mb-0 font-weight-bold">Phone</p>
                <p class="mb-4"><a href="#">+977 9808157822</a></p>
  
                <p class="mb-0 font-weight-bold">Email Address</p>
                <p class="mb-0"><a href="#">priyatamang565@gmail.com</a></p>
  
              </div>
            </div>
          </div>
        </div>
      </section>
{% endblock content %}

templates/Emp/employerhome.html
{% extends 'base.html' %} 
{% load static %}

{% block nav %} 

<!-- NAVBAR -->
<header class="site-navbar mt-3">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="site-logo col-6"><a href="/eindex/">JobBoard</a></div>
      
      
      

      <nav class="mx-auto site-navigation">
        <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
          <li><a href="/eindex/" class="nav-link active">Home</a></li>
          <li><a href="/eabout/">About</a></li>
          <li class="has-children">
            {% comment %} <a href="job-listings.html">Categories</a>
            <ul class="dropdown">
              <li><a href="job-single.html">Job Single</a></li>
              <li><a href="post-job.html">Post a Job</a></li>
            </ul> {% endcomment %}
          </li>
          {% comment %} <li class="has-children">
            <a href="#">Register</a>
            <ul class="dropdown">
              <li><a href="/eregister/">Employee</a></li>
              <li><a href="/jregister/">Jobseeks</a></li>
              
            </ul>
          </li> 
          {% comment %} <li><a href="blog.html">Blog</a></li> {% endcomment %}
          <li><a href="/econtact/">Contact</a></li>
          <li class="d-lg-none"><a href="/postjob/"><span class="mr-2">+</span> Post a Job</a></li>
          <li class="d-lg-none"><a href="/logout/">Logout</a></li>
           
          {% comment %} <li><a href="blog.html">Blog</a></li> {% endcomment %}
        </ul>
      </nav>
      
      <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
        <div class="ml-auto">
          <a href="/postjob/" class="btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-add"></span>Post a Job</a>
          <a href='/logout/' class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-lock_outline"></span>Logout</a>
          
           {% comment %} <li class="has-children">
            <a href="#">Register</a>
            <ul class="dropdown">
              <li><a href="/eregister/">Employee</a></li>
              <li><a href="/jregister/">Jobseeks</a></li>
              
            </ul>
          </li> {% endcomment %}
          {% comment %} <li><a href="blog.html">Blog</a></li> {% endcomment %}
        </div>
        </div>
        <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span></a>
      </div>

    </div>
  </div>
</header>
{% endblock nav %}

{% block content %} 

 <!-- HOME -->
 <section class="home-section section-hero overlay bg-image" style="background-image: url('/static/images/job/hero_1.jpg');" id="home-section">

  <div class="container">
    <div class="row align-items-center justify-content-center">
      <div class="col-md-12">
        <div class="mb-5 text-center">
          <h1 class="text-white font-weight-bold">Hello {{user.username}}</h1>
          <p>Find your perfect Employee for your Company...</p>
        </div>
        <form method="post" class="search-jobs-form">
          <div class="row mb-5">
            <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
              <input type="text" class="form-control form-control-lg" placeholder="Job title, Company...">
            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
              <select class="selectpicker" data-style="btn-white btn-lg" data-width="100%" data-live-search="true" title="Select Region">
                <option>Anywhere</option>
                <option>San Francisco</option>
                <option>Palo Alto</option>
                <option>New York</option>
                <option>Manhattan</option>
                <option>Ontario</option>
                <option>Toronto</option>
                <option>Kansas</option>
                <option>Mountain View</option>
              </select>
            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
              <select class="selectpicker" data-style="btn-white btn-lg" data-width="100%" data-live-search="true" title="Select Job Type">
                <option>Part Time</option>
                <option>Full Time</option>
              </select>
            </div>
            <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
              <button type="submit" class="btn btn-primary btn-lg btn-block text-white btn-search"><span class="icon-search icon mr-2"></span>Search Job</button>
            </div>
          </div>
          {% comment %} <div class="row">
            <div class="col-md-12 popular-keywords">
              <h3>Trending Keywords:</h3>
              <ul class="keywords list-unstyled m-0 p-0">
                <li><a href="#" class="">UI Designer</a></li>
                <li><a href="#" class="">Python</a></li>
                <li><a href="#" class="">Developer</a></li>
              </ul>
            </div>
          </div> {% endcomment %}
        </form>
      </div>
    </div>
  </div>

  <a href="#next" class="scroll-button smoothscroll">
    <span class=" icon-keyboard_arrow_down"></span>
  </a>

</section>

<section class="py-5 bg-image overlay-primary fixed overlay" id="next" style="background-image: url=("{% static '/static/images/job/hero_1.jpg' %}");">
  <div class="container">
    <div class="row mb-5 justify-content-center">
      <div class="col-md-7 text-center">
        <h2 class="section-title mb-2 text-white">JobBoard Site Stats</h2>
        <p class="lead text-white">Because people are our most precious assets… We only let the best managers in the world lead them</p>
      </div>
    </div>
    <div class="row pb-0 block__19738 section-counter">

      <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
        <div class="d-flex align-items-center justify-content-center mb-2">
          <strong class="number" data-number="1930">0</strong>
        </div>
        <span class="caption">Candidates</span>
      </div>

      <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
        <div class="d-flex align-items-center justify-content-center mb-2">
          <strong class="number" data-number="54">0</strong>
        </div>
        <span class="caption">Jobs Posted</span>
      </div>

      <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
        <div class="d-flex align-items-center justify-content-center mb-2">
          <strong class="number" data-number="120">0</strong>
        </div>
        <span class="caption">Jobs Filled</span>
      </div>

      <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
        <div class="d-flex align-items-center justify-content-center mb-2">
          <strong class="number" data-number="550">0</strong>
        </div>
        <span class="caption">Companies</span>
      </div>

        
    </div>
  </div>
</section>



<section class="site-section">
  <div class="container">

    <div class="row mb-5 justify-content-center">
      <div class="col-md-7 text-center">
        <h2 class="section-title mb-2">43,167 Job Listed</h2>
      </div>
    </div>
    {% for n in newjob %}
    <ul class="job-listings mb-5">
      <li class="job-listing d-block d-sm-flex pb-3 pb-sm-0 align-items-center">
        <a href="{% url 'Apps:empsinglejob' n.id %}"></a>
        <div class="job-listing-logo">
          {% if n.logo %}
          <img src="{{n.logo.url}}" alt="Free Website Template by Free-Template.co" class="img-fluid">
          {% endif %}
        </div>
        

        <div class="job-listing-about d-sm-flex custom-width w-100 justify-content-between mx-4">
          <div class="job-listing-position custom-width w-50 mb-3 mb-sm-0">
            <h2>{{n.job_title}}</h2>
            <strong>{{n.company_name}}</strong> 
          </div>
          <div class="job-listing-location mb-3 mb-sm-0 custom-width w-25">
            <span class="icon-room"></span> {{n.location}}
          </div>
          <div class="job-listing-meta">
            <span class="badge badge-danger">{{n.job_type}}</span>
            {% comment %} <span class="badge badge-danger">{{n.job_type}}</span> {% endcomment %}
          </div>
        </div>        
      </li>

        {% endfor %}

    
    <div class="row pagination-wrap">
      <div class="col-md-6 text-center text-md-left mb-4 mb-md-0">
        <span>Showing 1-7 Of 43,167 Jobs</span>
      </div>
      <div class="col-md-6 text-center text-md-right">
        <div class="custom-pagination ml-auto">
          <a href="#" class="prev">Prev</a>
          <div class="d-inline-block">
          <a href="#" class="active">1</a>
          <a href="#">2</a>
          <a href="#">3</a>
          <a href="#">4</a>
          </div>
          <a href="#" class="next">Next</a>
        </div>
      </div>
    </div>

  </div>
</section>

<section class="py-5 bg-image overlay-primary fixed overlay" style="background-image: url('static/images/job/hero_1.jpg');">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-8">
        <h2 class="text-white">Looking For A Job?</h2>
        <p class="mb-0 text-white lead">You can actually invent things here
        </p>
      </div>
      <div class="col-md-3 ml-auto">
        <a href="/login/" class="btn btn-warning btn-block btn-lg">Log In</a>
      </div>
    </div>
  </div>
</section>


{% endblock content %}

templates/Emp/esinglejob.html
{% extends 'base.html' %} 
{% load static %}

{% block nav %} 
<!-- NAVBAR -->
<header class="site-navbar mt-3">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="site-logo col-6"><a href="/">JobBoard</a></div>

      <nav class="mx-auto site-navigation">
        <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
          <li><a href="/eindex/" class="nav-link active">Home</a></li>
          <li><a href="/eabout">About</a></li>
          <li class="has-children">
            {% comment %} <a href="job-listings.html">Categories</a>
            <ul class="dropdown">
              <li><a href="job-single.html">Job Single</a></li>
              <li><a href="post-job.html">Post a Job</a></li>
            </ul> {% endcomment %}
          </li>
          {% comment %} <li class="has-children">
            <a href="#">Register</a>
            <ul class="dropdown">
              <li><a href="/eregister/">Employee</a></li>
              <li><a href="/jregister/">Jobseeks</a></li> 
              
            </ul>
          </li> {% endcomment %}
          {% comment %} <li><a href="blog.html">Blog</a></li> {% endcomment %}
          <li><a href="/econtact/">Contact</a></li>
          <li class="d-lg-none"><a href="/postjob/"><span class="mr-2">+</span> Post a Job</a></li>
          <li class="d-lg-none"><a href="/login/">Logout</a></li>
        </ul>
      </nav>
      
      <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
        <div class="ml-auto">
          <a href="/postjob/" class="btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-add"></span>Post a Job</a>
          <a href='/logout/' class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-lock_outline"></span>Logout</a>
        </div>
        <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span></a>
      </div>

    </div>
  </div>
</header>
{% endblock nav %}

{% block content %} 
   <!-- HOME -->
   <section class="section-hero overlay inner-page bg-image" style="background-image: url('/static/images/job/hero_1.jpg');" id="home-section">
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <h1 class="text-white font-weight-bold">{{job.job_title}}</h1>
          <div class="custom-breadcrumbs">
            <a href="#">Home</a> <span class="mx-2 slash">/</span>
            <a href="#">Job</a> <span class="mx-2 slash">/</span>
            <span class="text-white"><strong>{{job.job_title}}</strong></span>
            
          </div>
          
        </div>
      </div>
    </div>
  </section>

  
  <section class="site-section">
    <div class="container">
      <div class="row align-items-center mb-5">
        <div class="col-lg-8 mb-4 mb-lg-0">
          <div class="d-flex align-items-center">
            {% comment %} <div class="border p-2 d-inline-block mr-3 rounded">
              {% comment %} <img src="{{n.logo.url}}" alt="Image"> 
            </div> {% endcomment %}
            <div>
              <h2>{{job.job_title}}</h2>
              <div>
                <span class="ml-0 mr-2 mb-2"><span class="icon-briefcase mr-2"></span>{{job.company_name}}</span>
                <span class="m-2"><span class="icon-room mr-2"></span>{{job.location}}</span>
                <span class="m-2"><span class="icon-clock-o mr-2"></span><span class="text-primary">{{job.job_type}}</span></span>
              </div>
            </div>
          </div>
        </div>
        
        <div class="col-lg-4">
          <div class="row">
            <div class="col-6">
              {% comment %} <a href="#" class="btn btn-block btn-light btn-md"><span class="icon-heart-o mr-2 text-danger"></span>Save Job</a> {% endcomment %}
            </div>
            <div class="col-6">
              {% comment %} <a href="#" class="btn btn-block btn-primary btn-md">Apply Now</a> {% endcomment %}
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-8">
          <div class="mb-5">
            {% comment %} <figure class="mb-5"><img src="images/job_single_img_1.jpg" alt="Image" class="img-fluid rounded"></figure> {% endcomment %}
            <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span class="icon-align-left mr-3"></span>Job Description</h3>
            <p>{{job.job_description}}</p>
          </div>
          <div class="mb-5">
            <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span class="icon-rocket mr-3"></span>Responsibilities</h3>
            {% comment %} <ul class="list-unstyled m-0 p-0">
              <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>Necessitatibus quibusdam facilis</span></li>
              <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>Velit unde aliquam et voluptas reiciendis n Velit unde aliquam et voluptas reiciendis non sapiente labore</span></li>
              <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>Commodi quae ipsum quas est itaque</span></li>
              <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit</span></li>
              <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>Deleniti asperiores blanditiis nihil quia officiis dolor</span></li>
            </ul> {% endcomment %}
            <p>{{job.responsibilites}}</p>
          </div>

          <div class="mb-5">
            <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span class="icon-book mr-3"></span>Education + Experience</h3>
            {% comment %} <ul class="list-unstyled m-0 p-0">
              <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>Necessitatibus quibusdam facilis</span></li>
              <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>Velit unde aliquam et voluptas reiciendis non sapiente labore</span></li>
              <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>Commodi quae ipsum quas est itaque</span></li>
              <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit</span></li>
              <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>Deleniti asperiores blanditiis nihil quia officiis dolor</span></li>
            </ul> {% endcomment %}
            <p>{{job.eduction_experiance}}</p>
          </div>

          <div class="mb-5">
            <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span class="icon-turned_in mr-3"></span>Other Benifits</h3>
            {% comment %} <ul class="list-unstyled m-0 p-0">
              <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>Necessitatibus quibusdam facilis</span></li>
              <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>Velit unde aliquam et voluptas reiciendis non sapiente labore</span></li>
              <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>Commodi quae ipsum quas est itaque</span></li>
              <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit</span></li>
              <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>Deleniti asperiores blanditiis nihil quia officiis dolor</span></li>
            </ul> {% endcomment %}
            <p>{{job.other_benifits}}</p>

          </div>

          <div class="row mb-5">
            <div class="col-6">
              {% comment %} <a href="#" class="btn btn-block btn-light btn-md"><span class="icon-heart-o mr-2 text-danger"></span>Save Job</a> {% endcomment %}
            </div>
            <div class="col-6">
              {% comment %} <a href="{% url 'Apps:apply' job.id %}" class="btn btn-block btn-primary btn-md">Apply Now</a> {% endcomment %}
            </div>
          </div>

        </div>
        <div class="col-lg-4">
          <div class="bg-light p-3 border rounded mb-4">
            <h3 class="text-primary  mt-3 h5 pl-3 mb-3 ">Job Summary</h3>
            <ul class="list-unstyled pl-3 mb-0">
              <li class="mb-2"><strong class="text-black">Published on:</strong> {{job.published_on}}</li>
              <li class="mb-2"><strong class="text-black">Vacancy:</strong> {{job.vacancy}}</li>
              <li class="mb-2"><strong class="text-black">Employment Status:</strong> {{job.job_type}}</li>
              <li class="mb-2"><strong class="text-black">Experience:</strong> {{job.experience}} year</li>
              <li class="mb-2"><strong class="text-black">Job Location:</strong> {{job.location}}</li>
              <li class="mb-2"><strong class="text-black">Salary:</strong> {{job.salary}}</li>
              <li class="mb-2"><strong class="text-black">Gender:</strong> {{job.gender}}</li>
              <li class="mb-2"><strong class="text-black">Application Deadline:</strong> {{job.deadline}}</li>
            </ul>
          </div>
        

          <div class="bg-light p-3 border rounded">
            <h3 class="text-primary  mt-3 h5 pl-3 mb-3 ">Share</h3>
            <div class="px-3">
              <a href="#" class="pt-3 pb-3 pr-3 pl-0"><span class="icon-facebook"></span></a>
              <a href="#" class="pt-3 pb-3 pr-3 pl-0"><span class="icon-twitter"></span></a>
              <a href="#" class="pt-3 pb-3 pr-3 pl-0"><span class="icon-linkedin"></span></a>
              <a href="#" class="pt-3 pb-3 pr-3 pl-0"><span class="icon-pinterest"></span></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}